# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localvision < Formula
  desc "Local vision-language model tools for text-only coding LLMs, backed by a local llama.cpp subprocess."
  homepage "https://github.com/froggeric/llm/tree/main/mcp/localvision"
  version "0.3.0"
  license "PolyForm-Noncommercial-1.0.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/froggeric/llm/releases/download/v0.3.0/localvision_darwin-arm64.tar.gz"
    sha256 "353f28318d36435106637003343771d23ae9b078651d0312e33a04f72019e263"

    define_method(:install) do
      bin.install "localvision"
    end
  end

  def caveats
    <<~EOS
      localvision shells out to llama-server. Install it via `brew install llama.cpp`
      so `llama-server` is on your $PATH, or let localvision download a pinned
      release on first run.
    EOS
  end

  test do
    system "#{bin}/localvision", "version"
  end
end
